spring.application.name=movie

server.port=8001

# Importa el archivo .env (credenciales AWS) como properties
spring.config.import=optional:file:.env[.properties]


spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/movies}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.jakarta.persistence.validation.mode=none
jwt.secret=MiClaveSecretaQueDebeSerMuyLargaParaHMACSHA2561234567890

# AWS S3
aws.s3.bucket=app-spring-images-bucket
aws.s3.region=us-east-1
# server.error.include-stacktrace=never

#acento:
spring.thymeleaf.encoding=UTF-8
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true
