spring.application.name=springcloud.kafka
server.port=8080
spring.cloud.stream.bindings.commands-out-0.destination=products.commands
spring.cloud.stream.bindings.commands-out-0.contentType=application/json
spring.cloud.stream.kafka.binder.brokers=localhost:9092