spring.application.name=springcloud.kafka
server.port=8080
spring.cloud.stream.bindings.commands-out-0.destination=products.commands
spring.cloud.stream.bindings.commands-out-0.contentType=application/json
spring.cloud.stream.kafka.binder.brokers=kafka:19092

spring.cloud.function.definition=handleReplies
spring.cloud.stream.bindings.handleReplies-in-0.destination=products.replies
spring.cloud.stream.bindings.handleReplies-in-0.contentType=application/json
spring.cloud.stream.bindings.handleReplies-in-0.group=products-api
spring.cloud.stream.kafka.bindings.handleReplies-in-0.consumer.startOffset=latest