spring.application.name=products-command
server.port=8081
spring.cloud.function.definition=handleCommands

spring.cloud.stream.bindings.handleCommands-in-0.destination=products.commands
spring.cloud.stream.bindings.handleCommands-in-0.contentType=application/json

spring.cloud.stream.kafka.binder.brokers=localhost:9092
